// This file is auto-generated by ArgTransformer. Do not edit it manually!

export enum AppDisplayLang {
	kurmanci = 'kmr',
	english = 'en',
	german = 'de',
	turkish = 'tr',
}
export enum PostType {
	post = 'post',
	page = 'page',
}
export enum PostStatus {
	draft = 'draft',
	published = 'publish',
	archived = 'archived',
}
export enum KeyValueKey {
	siteTitle = 'siteTitle',
	siteDesc = 'siteDesc',
	mainMenu = 'mainMenu',
	mobileMenu = 'mobileMenu',
	homeSlider = 'homeSlider',
	androidUrl = 'androidUrl',
	iosUrl = 'iosUrl',
	facebookAppId = 'facebookAppId',
	facebookUrl = 'facebookUrl',
	instagramUrl = 'instagramUrl',
	twitterUrl = 'twitterUrl',
	youtubeUrl = 'youtubeUrl',
	whatsappNumber = 'whatsappNumber',
	telegramNumber = 'telegramNumber',
	contactEmail = 'contactEmail',
	notificationEmails = 'notificationEmails',
}
export enum SpecialPage {
	home_page = '/',
	posts = '/posts',
	advanced_search = '/advanced-search',
	about_us = '/about',
	contact = '/contact',
}
export enum UserRole {
	editor = 5,
	admin = 9,
	superadmin = 11,
}
export enum MenuItemType {
	link = 'link',
	post = 'post',
	page = 'page',
	special_page = 'special_page',
}